Adapt member page layout
everypolitician-scrapers/ghana-parliament pull request #10
Opened 2017-06-29 11:33 UTC by ondenman

This is a step towards adapting the scraper for the new page layout.

This PR makes changes to the MemberPage class so that it captures data from the new page layout correctly. I have dropped four fields --  Id, name, party and constituency -- as this data will be captured from the members list page.

This PR was originally part of https://github.com/everypolitician-scrapers/ghana-parliament/pull/7

2017-07-05 11:32 UTC, tmtmtmtm requested changes
Mostly good, except for the odd Constituency field

2017-07-05 11:32 UTC, tmtmtmtm commented on test/data/mps?mp=265.yml
> +  :constituency: MP for Yagaba-Kubori constituency, Northern region
That doesn't look like what we'd want `constituency` to return…

2017-07-05 11:32 UTC, tmtmtmtm commented on lib/member_page.rb
> +    box.xpath('//b[contains(text(),"%s")]/following::td' % text)
as every place that calls this immediately calls `.first` on the return value, it might be worth adding that here instead

2017-07-05 11:32 UTC, tmtmtmtm commented on lib/member_page.rb
> +    url[/\d+/]
I'm curious why you changed this one. Is there a scenario now where that _isn't_ at the end? Would be worth adding a test-case for that if so.

2017-07-06 13:51 UTC, ondenman commented on lib/member_page.rb
> +    url[/\d+/]
I don't think I meant to remove that on purpose. I've added it back in.

2017-07-06 22:30 UTC, tmtmtmtm requested changes
Having a question mark in a filename is generally a bad idea, as it's a reserved character in some operating systems. I don't think there's any value in naming the file `mps?mp=265.yml` rather than just, say, `265.yml`.

2017-07-07 09:04 UTC, ondenman commented
I've amended the fix up to change the test file name.

2017-07-14 07:08 UTC, tmtmtmtm commented on lib/member_page.rb
> +    box.css('center').text[/(?<= MP\ for)(.*)/].tidy.chomp('.')
This is quite over-complex. This would be much simpler as `text[/MP for (.*)/, 1]`

2017-07-14 07:11 UTC, tmtmtmtm approved these changes

2017-07-14 07:11 UTC, merged